version: "3.8"

services:
  app:
    image: beenguyen0601/mall-shop:prod
    container_name: mall-shop
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    external: true
