version: '3.8'

services:
  app:
    image: beenguyen0601/mall-shop:prod
    container_name: mall-shop
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    networks:
      - app-net

networks:
  app-net:
    external: true
