services:
  app:
    build:
      context: .
    container_name: mall-shop
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    external: true
